version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: no
    environment:
      - POSTGRES_USER=authuser
      - POSTGRES_PASSWORD=authpassword
      - POSTGRES_DB=auth-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5430:5432'

volumes:
  postgres:

